# Generated by Django 4.1.7 on 2023-05-18 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compilator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
