# Generated by Django 4.1.7 on 2023-05-25 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compilator', '0002_remove_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContextContainer',
        ),
    ]
