# Generated by Django 4.1.7 on 2023-05-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilator', '0005_remove_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
